name               = "tab-stasher"
main               = ".open-next/worker.js"
compatibility_date = "2025-07-06"
compatibility_flags = ["nodejs_compat"]

[vars]
  # your NEXTAUTH_URL, SUPABASE_URL, etc.

# if you need any secrets:
# (run `wrangler secret put FOO` for each one instead of hard-coding here)

[assets]
binding   = "ASSETS"
directory = ".open-next/assets"