// Background script for Tab Stasher Chrome Extension
// Handles tab processing and communication with the Tab Stasher API

class TabStasherBackground {
  constructor() {
    this.apiBaseUrl = 'https://tab-stasher.tab-stasher.workers.dev';
    this.setupMessageHandlers();
  }

  setupMessageHandlers() {
    chrome.runtime.onMessage.addListener((request, sender, sendResponse) => {
      switch (request.action) {
        case 'saveTab':
          this.saveTab(request.tabData, sender.tab)
            .then(result => sendResponse({ success: true, data: result }))
            .catch(error => sendResponse({ success: false, error: error.message }));
          return true; // Keep message channel open for async response

        case 'getTabInfo':
          this.getTabInfo(sender.tab)
            .then(result => sendResponse({ success: true, data: result }))
            .catch(error => sendResponse({ success: false, error: error.message }));
          return true;

        case 'checkAuth':
          this.checkAuthentication()
            .then(result => sendResponse(result))
            .catch(error => sendResponse({ isAuthenticated: false, error: error.message }));
          return true;

        case 'handleAuth':
          this.handleAuth();
          sendResponse({ success: true });
          break;

        case 'logout':
          this.performLogout();
          sendResponse({ success: true });
          break;

        case 'showNotification':
          this.showNotification(request.title, request.message, request.type);
          break;

        default:
          sendResponse({ success: false, error: 'Unknown action' });
      }
    });
  }

  isValidUrl(url) {
    try {
      const urlObj = new URL(url);
      // Only allow http and https protocols
      return urlObj.protocol === 'http:' || urlObj.protocol === 'https:';
    } catch (error) {
      return false;
    }
  }

  async getTabInfo(tab) {
    try {
      // Extract basic tab information
      const tabData = {
        url: tab.url,
        title: tab.title,
        favicon: tab.favIconUrl || null
      };

      // Try to get additional page content if possible
      try {
        const response = await chrome.tabs.sendMessage(tab.id, { action: 'getPageContent' });
        if (response && response.success) {
          return {
            ...tabData,
            description: response.data.description,
            image: response.data.image,
            content: response.data.content
          };
        }
      } catch (error) {
        console.log('Could not get page content:', error);
      }

      return tabData;
    } catch (error) {
      throw new Error(`Failed to get tab info: ${error.message}`);
    }
  }

  async saveTab(tabData, tab) {
    try {
      // Validate URL
      if (!this.isValidUrl(tabData.url)) {
        throw new Error('Invalid tab URL. Only http and https URLs are supported.');
      }

      // Check if user is authenticated by testing the API
      const authCheck = await this.checkAuthentication();

      if (!authCheck.isAuthenticated) {
        throw new Error('User not authenticated. Please log in to Tab Stasher.');
      }

      // Prepare the request payload
      const payload = {
        url: tabData.url,
        title: tabData.title || 'Untitled',
        description: tabData.description || '',
        image: tabData.image || null,
        favicon: tabData.favicon || null,
        content: tabData.content || '',
        tags: [], // Will be auto-generated by the API
        primaryCategory: 'uncategorized',
        secondaryCategory: 'general',
        confidence: 0.5
      };

      // Send to Tab Stasher API (no Authorization header needed - uses cookies)
      const controller = new AbortController();
      const timeoutId = setTimeout(() => controller.abort(), 10000); // 10 second timeout

      const response = await fetch(`${this.apiBaseUrl}/api/tabs`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json'
        },
        credentials: 'include', // Include cookies for authentication
        body: JSON.stringify(payload),
        signal: controller.signal
      });

      clearTimeout(timeoutId);

      if (!response.ok) {
        let errorMessage = `HTTP ${response.status}: ${response.statusText}`;
        try {
          const errorData = await response.json();
          errorMessage = errorData.error || errorMessage;
        } catch (parseError) {
          // If response body can't be parsed, use the status message
          console.log('Could not parse error response:', parseError);
        }
        throw new Error(errorMessage);
      }

      const result = await response.json();
      
      // Show success notification
      this.showNotification(
        'Tab Saved!',
        `"${tabData.title}" has been saved to your Tab Stasher collection.`,
        'success'
      );

      return result;
    } catch (error) {
      console.error('Error saving tab:', error);
      
      // Show error notification
      this.showNotification(
        'Save Failed',
        error.message,
        'error'
      );
      
      throw error;
    }
  }

  performLogout() {
    try {
      console.log('Performing logout...');

      // Clear extension storage
      chrome.storage.local.remove(['authCompletedAt']);

      // Optionally open the login page so user can manually log out if needed
      // This allows the app's logout flow to complete properly
      chrome.tabs.create({
        url: `${this.apiBaseUrl}/login`
      }).catch(error => {
        console.log('Could not open login page:', error.message);
      });

      this.showNotification(
        'Logged Out',
        'You have been logged out. Please log in again to continue.',
        'info'
      );
    } catch (error) {
      console.error('Error during logout:', error);
      this.showNotification(
        'Logout Error',
        error.message,
        'error'
      );
    }
  }

  showNotification(title, message, type = 'info') {
    // Create notification
    chrome.notifications.create({
      type: 'basic',
      iconUrl: 'icons/icon48.png',
      title: title,
      message: message
    });

    // Also send to content script to show mini-toast
    chrome.tabs.query({ active: true, currentWindow: true }, (tabs) => {
      if (tabs[0]) {
        chrome.tabs.sendMessage(tabs[0].id, {
          action: 'showToast',
          title: title,
          message: message,
          type: type
        }).catch(error => {
          // Ignore errors if content script doesn't exist
          console.log('Could not send message to content script:', error.message);
        });
      }
    });
  }

  async checkAuthentication() {
    try {
      // Try the dedicated auth check endpoint first
      const controller = new AbortController();
      const timeoutId = setTimeout(() => controller.abort(), 5000); // 5 second timeout

      console.log('Checking authentication with /api/auth/check endpoint...');

      try {
        const response = await fetch(`${this.apiBaseUrl}/api/auth/check`, {
          method: 'GET',
          credentials: 'include',
          headers: {
            'Accept': 'application/json',
            'Content-Type': 'application/json'
          },
          signal: controller.signal
        });

        clearTimeout(timeoutId);

        if (response.ok) {
          const data = await response.json();

          console.log('Auth check response:', {
            status: response.status,
            isAuthenticated: data.isAuthenticated,
            user: data.user?.email
          });

          return {
            isAuthenticated: data.isAuthenticated === true,
            status: response.status,
            user: data.user
          };
        }
      } catch (endpointError) {
        console.log('Primary auth endpoint failed, trying fallback...', endpointError.message);
        clearTimeout(timeoutId);
      }

      // Fallback: Use /api/tabs endpoint to check authentication
      console.log('Using fallback authentication check...');
      const fallbackController = new AbortController();
      const fallbackTimeoutId = setTimeout(() => fallbackController.abort(), 5000);

      const fallbackResponse = await fetch(`${this.apiBaseUrl}/api/tabs`, {
        method: 'POST',
        credentials: 'include',
        headers: {
          'Accept': 'application/json',
          'Content-Type': 'application/json'
        },
        body: JSON.stringify({ url: '' }),
        signal: fallbackController.signal
      });

      clearTimeout(fallbackTimeoutId);

      console.log('Fallback auth check response:', {
        status: fallbackResponse.status,
        ok: fallbackResponse.ok
      });

      // 401 = not authenticated
      // Anything else = authenticated (even 400 means auth passed, just bad data)
      const isAuthenticated = fallbackResponse.status !== 401;

      return {
        isAuthenticated: isAuthenticated,
        status: fallbackResponse.status,
        user: null
      };
    } catch (error) {
      console.error('Auth check error (both methods failed):', error);
      return {
        isAuthenticated: false,
        error: error.message
      };
    }
  }

  // Handle authentication with retry logic
  async handleAuth() {
    try {
      // Open Tab Stasher login page
      const tab = await chrome.tabs.create({
        url: `${this.apiBaseUrl}/login`
      });

      const listener = (tabId, changeInfo, updatedTab) => {
        if (tabId === tab.id && changeInfo.url) {
          console.log('Tab URL changed to:', changeInfo.url);

          // Check if we're on dashboard or any authenticated page
          if (changeInfo.url.includes('/dashboard') ||
              changeInfo.url.includes('/settings') ||
              changeInfo.url.includes('/auth/callback')) {

            // Retry auth check with exponential backoff
            this.retryAuthCheck(tabId, listener, 3);
          }
        }
      };

      chrome.tabs.onUpdated.addListener(listener);

      // Set a timeout to remove the listener after 5 minutes
      setTimeout(() => {
        chrome.tabs.onUpdated.removeListener(listener);
        console.log('Auth listener timeout - removing listener');
      }, 5 * 60 * 1000); // 5 minutes

    } catch (error) {
      console.error('Auth error:', error);
    }
  }

  // Retry authentication check with exponential backoff
  async retryAuthCheck(tabId, listener, attemptsRemaining, delayMs = 1000) {
    try {
      // Wait before checking
      await new Promise(resolve => setTimeout(resolve, delayMs));

      const authCheck = await this.checkAuthentication();
      console.log('Auth check attempt:', {
        status: authCheck.status,
        isAuthenticated: authCheck.isAuthenticated,
        delayMs,
        attemptsRemaining,
        error: authCheck.error
      });

      if (authCheck.isAuthenticated) {
        // Auth completed successfully
        console.log('✅ Authentication successful!');

        chrome.tabs.remove(tabId).catch(error => {
          console.log('Could not close auth tab:', error.message);
        });
        chrome.tabs.onUpdated.removeListener(listener);

        // Store auth completion timestamp for popup to check
        chrome.storage.local.set({
          authCompletedAt: Date.now(),
          isAuthenticated: true
        });

        // Try to send message to popup (if open)
        chrome.runtime.sendMessage({
          action: 'authCompleted'
        }).catch(error => {
          // Ignore errors if popup is not open
          console.log('Could not send auth completion message:', error.message);
        });
      } else if (attemptsRemaining > 0) {
        // Retry with exponential backoff (1s, 1.5s, 2.25s)
        const nextDelay = delayMs * 1.5;
        console.log(`⏳ Auth check failed, retrying in ${nextDelay}ms (${attemptsRemaining} attempts remaining)`);
        this.retryAuthCheck(tabId, listener, attemptsRemaining - 1, nextDelay);
      } else {
        console.log('❌ Auth check failed after maximum attempts');
        chrome.tabs.onUpdated.removeListener(listener);
        // Note: Tab will remain open for user to complete login manually if needed
      }
    } catch (error) {
      console.error('❌ Error in retry auth check:', error);
      if (attemptsRemaining > 0) {
        const nextDelay = delayMs * 1.5;
        console.log(`⏳ Retrying after error in ${nextDelay}ms`);
        this.retryAuthCheck(tabId, listener, attemptsRemaining - 1, nextDelay);
      }
    }
  }
}

// Initialize the background script
new TabStasherBackground();

// Handle extension installation
chrome.runtime.onInstalled.addListener((details) => {
  if (details.reason === 'install') {
    console.log('Tab Stasher extension installed');
  }
});
